name: Run tests
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.13"]  
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
      - name: Test with pytest  
        run: |  
          coverage run -m pytest --datetime-increments-limit=150 -m "not completion"  
      - name: Generate coverage report  
        run: |  
          coverage report -m
      - name: Check annotations with mypy  
        run: |  
          mypy --strict ./MISOReports/MISOReports.py

